---
deployment:
  tasks:
    - export DEPLOYPATH=/home/beitragp/marketsnewstoday.info
    - /bin/cp -rf output/* $DEPLOYPATH/
    - /bin/cp style.css $DEPLOYPATH/style.css
    - /bin/cp robots.txt $DEPLOYPATH/robots.txt
